### ISSUE TITLE
EQ master - something wrong with bypass

### ISSUE THREAD

**Issue by vcvrackideas** [MarcBoule/MindMeldModular#87] opened 2021-12-25 11:54 UTC
Hi Marc and Merry Xmas! 
So I struggle with some strange issue that came time to time - eq doesn't do anything until I press bypass on the track twice, so do off and then on. And only then eq starts doing things. Have no better words how to describe the issue. 

Cheers!

**Comment by MarcBoule** [comment] 2021-12-25 14:29
Hi Artem, 
I've played around with the EQ a bit and unfortunately I can't see the issue. I don't doubt that you have spotted something wrong, but in order for us to debug this, we'll need a bit more info on your setup and how it can be reproduced. If it's an intermittent problem, it will be harder to debug, but we would at least need a minimal patch where you have the problem, and if we can play with that and make it happen, then it will be easier to narrow down what might be wrong.
Happy holidays to you also!
Wishing you great music production in 2022 :-)
Cheers,
Marc

**Comment by MarcBoule** [comment] 2022-04-18 12:10
Closing since we can't reproduce this. Please open again if you can find reproducible steps.

**Closed by MarcBoule** 2022-04-18 12:10 UTC
